import { act, renderHook } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { WorkSession } from '../../src/db/schema';
const mocks=vi.hoisted(()=>({createActiveSessionLifecycle:vi.fn()}));
vi.mock('../../src/lib/sessionLifecycle',()=>mocks);
import { useSessionLifecycle } from '../../src/lib/useSessionLifecycle';
const session=(id:string):WorkSession=>({id,createdAt:1,updatedAt:2,documents:[],templatePlacements:[]});
function controller(){const unsubscribe=vi.fn();return{subscribe:vi.fn(()=>unsubscribe),getState:vi.fn(()=>({ready:true,candidate:session('predecessor'),mode:'persistent' as const,warning:null})),startup:vi.fn().mockResolvedValue(undefined),observeRevision:vi.fn(),dismissCandidate:vi.fn(),startFresh:vi.fn(),dispose:vi.fn(),unsubscribe};}
describe('useSessionLifecycle',()=>{beforeEach(()=>mocks.createActiveSessionLifecycle.mockReset());it('starts, observes only contentRevision with latest session, forwards Start Fresh, and disposes',()=>{const lifecycle=controller();mocks.createActiveSessionLifecycle.mockReturnValue(lifecycle);const resetSession=vi.fn();const{result,rerender,unmount}=renderHook(({current,revision})=>useSessionLifecycle({session:current,contentRevision:revision,resetSession}),{initialProps:{current:session('one'),revision:1}});expect(lifecycle.startup).toHaveBeenCalledOnce();expect(lifecycle.observeRevision).toHaveBeenLastCalledWith(expect.objectContaining({id:'one'}),1);rerender({current:session('view-only'),revision:1});expect(lifecycle.observeRevision).toHaveBeenCalledTimes(1);rerender({current:session('latest'),revision:2});expect(lifecycle.observeRevision).toHaveBeenLastCalledWith(expect.objectContaining({id:'latest'}),2);act(()=>result.current.startFresh());expect(lifecycle.startFresh).toHaveBeenCalledWith('predecessor',resetSession);act(()=>result.current.resumeSucceeded());expect(lifecycle.dismissCandidate).toHaveBeenCalled();unmount();expect(lifecycle.unsubscribe).toHaveBeenCalled();expect(lifecycle.dispose).toHaveBeenCalled();});});
